import images from '~/assets/images';
const RANKINGS = [
    {
        rank: 1,
        avatar: images.ranking1,
        name: 'Cyan Fake Mutant Ape Yacht Club',
        floorPrice: 9,
        price: 9,
        percentageSlippage: null,
    },
    {
        rank: 2,
        avatar: images.ranking2,
        name: 'Azuki God',
        floorPrice: 0.5,
        price: 10.2,
        percentageSlippage: 40,
    },
    {
        rank: 3,
        avatar: images.ranking3,
        name: 'Sweet Pool - Public Testnet',
        floorPrice: 9,
        price: 5,
        percentageSlippage: null,
    },
    {
        rank: 4,
        avatar: images.ranking4,
        name: 'DOPE: Dawn Of the Pixel Empire',
        floorPrice: 0.8,
        price: 4.65,
        percentageSlippage: -2.11,
    },
    {
        rank: 5,
        avatar: images.ranking5,
        name: 'niubidaShaoye',
        floorPrice: 0.1,
        price: 3.32,
        percentageSlippage: +2578.58,
    },
    {
        rank: 6,
        avatar: images.ranking1,
        name: 'Cyan Fake Mutant Ape Yacht Club',
        floorPrice: 9,
        price: 9,
        percentageSlippage: null,
    },
    {
        rank: 7,
        avatar: images.ranking2,
        name: 'Azuki God',
        floorPrice: 0.5,
        price: 10.2,
        percentageSlippage: 40,
    },
    {
        rank: 8,
        avatar: images.ranking3,
        name: 'Sweet Pool - Public Testnet',
        floorPrice: 9,
        price: 5,
        percentageSlippage: null,
    },
    {
        rank: 9,
        avatar: images.ranking4,
        name: 'DOPE: Dawn Of the Pixel Empire',
        floorPrice: 0.8,
        price: 4.65,
        percentageSlippage: -2.11,
    },
    {
        rank: 10,
        avatar: images.ranking5,
        name: 'niubidaShaoye',
        floorPrice: 0.1,
        price: 3.32,
        percentageSlippage: +2578.58,
    },
    {
        rank: 11,
        avatar: images.ranking1,
        name: 'Cyan Fake Mutant Ape Yacht Club',
        floorPrice: 9,
        price: 9,
        percentageSlippage: null,
    },
    {
        rank: 12,
        avatar: images.ranking2,
        name: 'Azuki God',
        floorPrice: 0.5,
        price: 10.2,
        percentageSlippage: 40,
    },
    {
        rank: 13,
        avatar: images.ranking3,
        name: 'Sweet Pool - Public Testnet',
        floorPrice: 9,
        price: 5,
        percentageSlippage: null,
    },
    {
        rank: 14,
        avatar: images.ranking4,
        name: 'DOPE: Dawn Of the Pixel Empire',
        floorPrice: 0.8,
        price: 4.65,
        percentageSlippage: -2.11,
    },
    {
        rank: 15,
        avatar: images.ranking5,
        name: 'niubidaShaoye',
        floorPrice: 0.1,
        price: 3.32,
        percentageSlippage: +2578.58,
    },
];

export default RANKINGS;
